/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserRequestRouteImport } from './routes/user/request'
import { Route as UserHistoryRouteImport } from './routes/user/history'
import { Route as UserEditProfileRouteImport } from './routes/user/edit-profile'
import { Route as TechnicianReturnRouteImport } from './routes/technician/return'
import { Route as TechnicianRequestsRouteImport } from './routes/technician/requests'
import { Route as TechnicianRequestViewRouteImport } from './routes/technician/request-view'
import { Route as TechnicianRequestLogRouteImport } from './routes/technician/request-log'
import { Route as TechnicianRequestAssetsRouteImport } from './routes/technician/request-assets'
import { Route as TechnicianNetworkRouteImport } from './routes/technician/network'
import { Route as TechnicianLaptopRouteImport } from './routes/technician/laptop'
import { Route as TechnicianHistoryRouteImport } from './routes/technician/history'
import { Route as TechnicianDisposalRouteImport } from './routes/technician/disposal'
import { Route as TechnicianDeployRouteImport } from './routes/technician/deploy'
import { Route as TechnicianDashboardRouteImport } from './routes/technician/dashboard'
import { Route as TechnicianBulkImportRouteImport } from './routes/technician/bulk-import'
import { Route as TechnicianAvRouteImport } from './routes/technician/av'
import { Route as TechnicianAddAssetRouteImport } from './routes/technician/add-asset'
import { Route as TechnicianAssetKindAssetIdRouteImport } from './routes/technician/asset.$kind.$assetId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRequestRoute = UserRequestRouteImport.update({
  id: '/user/request',
  path: '/user/request',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/user/history',
  path: '/user/history',
  getParentRoute: () => rootRouteImport,
} as any)
const UserEditProfileRoute = UserEditProfileRouteImport.update({
  id: '/user/edit-profile',
  path: '/user/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianReturnRoute = TechnicianReturnRouteImport.update({
  id: '/technician/return',
  path: '/technician/return',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRequestsRoute = TechnicianRequestsRouteImport.update({
  id: '/technician/requests',
  path: '/technician/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRequestViewRoute = TechnicianRequestViewRouteImport.update({
  id: '/technician/request-view',
  path: '/technician/request-view',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRequestLogRoute = TechnicianRequestLogRouteImport.update({
  id: '/technician/request-log',
  path: '/technician/request-log',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRequestAssetsRoute = TechnicianRequestAssetsRouteImport.update({
  id: '/technician/request-assets',
  path: '/technician/request-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianNetworkRoute = TechnicianNetworkRouteImport.update({
  id: '/technician/network',
  path: '/technician/network',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianLaptopRoute = TechnicianLaptopRouteImport.update({
  id: '/technician/laptop',
  path: '/technician/laptop',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianHistoryRoute = TechnicianHistoryRouteImport.update({
  id: '/technician/history',
  path: '/technician/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianDisposalRoute = TechnicianDisposalRouteImport.update({
  id: '/technician/disposal',
  path: '/technician/disposal',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianDeployRoute = TechnicianDeployRouteImport.update({
  id: '/technician/deploy',
  path: '/technician/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianDashboardRoute = TechnicianDashboardRouteImport.update({
  id: '/technician/dashboard',
  path: '/technician/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianBulkImportRoute = TechnicianBulkImportRouteImport.update({
  id: '/technician/bulk-import',
  path: '/technician/bulk-import',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianAvRoute = TechnicianAvRouteImport.update({
  id: '/technician/av',
  path: '/technician/av',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianAddAssetRoute = TechnicianAddAssetRouteImport.update({
  id: '/technician/add-asset',
  path: '/technician/add-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianAssetKindAssetIdRoute =
  TechnicianAssetKindAssetIdRouteImport.update({
    id: '/technician/asset/$kind/$assetId',
    path: '/technician/asset/$kind/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/technician/add-asset': typeof TechnicianAddAssetRoute
  '/technician/av': typeof TechnicianAvRoute
  '/technician/bulk-import': typeof TechnicianBulkImportRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/deploy': typeof TechnicianDeployRoute
  '/technician/disposal': typeof TechnicianDisposalRoute
  '/technician/history': typeof TechnicianHistoryRoute
  '/technician/laptop': typeof TechnicianLaptopRoute
  '/technician/network': typeof TechnicianNetworkRoute
  '/technician/request-assets': typeof TechnicianRequestAssetsRoute
  '/technician/request-log': typeof TechnicianRequestLogRoute
  '/technician/request-view': typeof TechnicianRequestViewRoute
  '/technician/requests': typeof TechnicianRequestsRoute
  '/technician/return': typeof TechnicianReturnRoute
  '/user/edit-profile': typeof UserEditProfileRoute
  '/user/history': typeof UserHistoryRoute
  '/user/request': typeof UserRequestRoute
  '/technician/asset/$kind/$assetId': typeof TechnicianAssetKindAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/technician/add-asset': typeof TechnicianAddAssetRoute
  '/technician/av': typeof TechnicianAvRoute
  '/technician/bulk-import': typeof TechnicianBulkImportRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/deploy': typeof TechnicianDeployRoute
  '/technician/disposal': typeof TechnicianDisposalRoute
  '/technician/history': typeof TechnicianHistoryRoute
  '/technician/laptop': typeof TechnicianLaptopRoute
  '/technician/network': typeof TechnicianNetworkRoute
  '/technician/request-assets': typeof TechnicianRequestAssetsRoute
  '/technician/request-log': typeof TechnicianRequestLogRoute
  '/technician/request-view': typeof TechnicianRequestViewRoute
  '/technician/requests': typeof TechnicianRequestsRoute
  '/technician/return': typeof TechnicianReturnRoute
  '/user/edit-profile': typeof UserEditProfileRoute
  '/user/history': typeof UserHistoryRoute
  '/user/request': typeof UserRequestRoute
  '/technician/asset/$kind/$assetId': typeof TechnicianAssetKindAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/technician/add-asset': typeof TechnicianAddAssetRoute
  '/technician/av': typeof TechnicianAvRoute
  '/technician/bulk-import': typeof TechnicianBulkImportRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/deploy': typeof TechnicianDeployRoute
  '/technician/disposal': typeof TechnicianDisposalRoute
  '/technician/history': typeof TechnicianHistoryRoute
  '/technician/laptop': typeof TechnicianLaptopRoute
  '/technician/network': typeof TechnicianNetworkRoute
  '/technician/request-assets': typeof TechnicianRequestAssetsRoute
  '/technician/request-log': typeof TechnicianRequestLogRoute
  '/technician/request-view': typeof TechnicianRequestViewRoute
  '/technician/requests': typeof TechnicianRequestsRoute
  '/technician/return': typeof TechnicianReturnRoute
  '/user/edit-profile': typeof UserEditProfileRoute
  '/user/history': typeof UserHistoryRoute
  '/user/request': typeof UserRequestRoute
  '/technician/asset/$kind/$assetId': typeof TechnicianAssetKindAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/technician/add-asset'
    | '/technician/av'
    | '/technician/bulk-import'
    | '/technician/dashboard'
    | '/technician/deploy'
    | '/technician/disposal'
    | '/technician/history'
    | '/technician/laptop'
    | '/technician/network'
    | '/technician/request-assets'
    | '/technician/request-log'
    | '/technician/request-view'
    | '/technician/requests'
    | '/technician/return'
    | '/user/edit-profile'
    | '/user/history'
    | '/user/request'
    | '/technician/asset/$kind/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/technician/add-asset'
    | '/technician/av'
    | '/technician/bulk-import'
    | '/technician/dashboard'
    | '/technician/deploy'
    | '/technician/disposal'
    | '/technician/history'
    | '/technician/laptop'
    | '/technician/network'
    | '/technician/request-assets'
    | '/technician/request-log'
    | '/technician/request-view'
    | '/technician/requests'
    | '/technician/return'
    | '/user/edit-profile'
    | '/user/history'
    | '/user/request'
    | '/technician/asset/$kind/$assetId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/technician/add-asset'
    | '/technician/av'
    | '/technician/bulk-import'
    | '/technician/dashboard'
    | '/technician/deploy'
    | '/technician/disposal'
    | '/technician/history'
    | '/technician/laptop'
    | '/technician/network'
    | '/technician/request-assets'
    | '/technician/request-log'
    | '/technician/request-view'
    | '/technician/requests'
    | '/technician/return'
    | '/user/edit-profile'
    | '/user/history'
    | '/user/request'
    | '/technician/asset/$kind/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TechnicianAddAssetRoute: typeof TechnicianAddAssetRoute
  TechnicianAvRoute: typeof TechnicianAvRoute
  TechnicianBulkImportRoute: typeof TechnicianBulkImportRoute
  TechnicianDashboardRoute: typeof TechnicianDashboardRoute
  TechnicianDeployRoute: typeof TechnicianDeployRoute
  TechnicianDisposalRoute: typeof TechnicianDisposalRoute
  TechnicianHistoryRoute: typeof TechnicianHistoryRoute
  TechnicianLaptopRoute: typeof TechnicianLaptopRoute
  TechnicianNetworkRoute: typeof TechnicianNetworkRoute
  TechnicianRequestAssetsRoute: typeof TechnicianRequestAssetsRoute
  TechnicianRequestLogRoute: typeof TechnicianRequestLogRoute
  TechnicianRequestViewRoute: typeof TechnicianRequestViewRoute
  TechnicianRequestsRoute: typeof TechnicianRequestsRoute
  TechnicianReturnRoute: typeof TechnicianReturnRoute
  UserEditProfileRoute: typeof UserEditProfileRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserRequestRoute: typeof UserRequestRoute
  TechnicianAssetKindAssetIdRoute: typeof TechnicianAssetKindAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/request': {
      id: '/user/request'
      path: '/user/request'
      fullPath: '/user/request'
      preLoaderRoute: typeof UserRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/history': {
      id: '/user/history'
      path: '/user/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/edit-profile': {
      id: '/user/edit-profile'
      path: '/user/edit-profile'
      fullPath: '/user/edit-profile'
      preLoaderRoute: typeof UserEditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/return': {
      id: '/technician/return'
      path: '/technician/return'
      fullPath: '/technician/return'
      preLoaderRoute: typeof TechnicianReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/requests': {
      id: '/technician/requests'
      path: '/technician/requests'
      fullPath: '/technician/requests'
      preLoaderRoute: typeof TechnicianRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/request-view': {
      id: '/technician/request-view'
      path: '/technician/request-view'
      fullPath: '/technician/request-view'
      preLoaderRoute: typeof TechnicianRequestViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/request-log': {
      id: '/technician/request-log'
      path: '/technician/request-log'
      fullPath: '/technician/request-log'
      preLoaderRoute: typeof TechnicianRequestLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/request-assets': {
      id: '/technician/request-assets'
      path: '/technician/request-assets'
      fullPath: '/technician/request-assets'
      preLoaderRoute: typeof TechnicianRequestAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/network': {
      id: '/technician/network'
      path: '/technician/network'
      fullPath: '/technician/network'
      preLoaderRoute: typeof TechnicianNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/laptop': {
      id: '/technician/laptop'
      path: '/technician/laptop'
      fullPath: '/technician/laptop'
      preLoaderRoute: typeof TechnicianLaptopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/history': {
      id: '/technician/history'
      path: '/technician/history'
      fullPath: '/technician/history'
      preLoaderRoute: typeof TechnicianHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/disposal': {
      id: '/technician/disposal'
      path: '/technician/disposal'
      fullPath: '/technician/disposal'
      preLoaderRoute: typeof TechnicianDisposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/deploy': {
      id: '/technician/deploy'
      path: '/technician/deploy'
      fullPath: '/technician/deploy'
      preLoaderRoute: typeof TechnicianDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/dashboard': {
      id: '/technician/dashboard'
      path: '/technician/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof TechnicianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/bulk-import': {
      id: '/technician/bulk-import'
      path: '/technician/bulk-import'
      fullPath: '/technician/bulk-import'
      preLoaderRoute: typeof TechnicianBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/av': {
      id: '/technician/av'
      path: '/technician/av'
      fullPath: '/technician/av'
      preLoaderRoute: typeof TechnicianAvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/add-asset': {
      id: '/technician/add-asset'
      path: '/technician/add-asset'
      fullPath: '/technician/add-asset'
      preLoaderRoute: typeof TechnicianAddAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/asset/$kind/$assetId': {
      id: '/technician/asset/$kind/$assetId'
      path: '/technician/asset/$kind/$assetId'
      fullPath: '/technician/asset/$kind/$assetId'
      preLoaderRoute: typeof TechnicianAssetKindAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TechnicianAddAssetRoute: TechnicianAddAssetRoute,
  TechnicianAvRoute: TechnicianAvRoute,
  TechnicianBulkImportRoute: TechnicianBulkImportRoute,
  TechnicianDashboardRoute: TechnicianDashboardRoute,
  TechnicianDeployRoute: TechnicianDeployRoute,
  TechnicianDisposalRoute: TechnicianDisposalRoute,
  TechnicianHistoryRoute: TechnicianHistoryRoute,
  TechnicianLaptopRoute: TechnicianLaptopRoute,
  TechnicianNetworkRoute: TechnicianNetworkRoute,
  TechnicianRequestAssetsRoute: TechnicianRequestAssetsRoute,
  TechnicianRequestLogRoute: TechnicianRequestLogRoute,
  TechnicianRequestViewRoute: TechnicianRequestViewRoute,
  TechnicianRequestsRoute: TechnicianRequestsRoute,
  TechnicianReturnRoute: TechnicianReturnRoute,
  UserEditProfileRoute: UserEditProfileRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserRequestRoute: UserRequestRoute,
  TechnicianAssetKindAssetIdRoute: TechnicianAssetKindAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
