/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicianReturnRouteImport } from './routes/technician/return'
import { Route as TechnicianNetworkRouteImport } from './routes/technician/network'
import { Route as TechnicianLaptopRouteImport } from './routes/technician/laptop'
import { Route as TechnicianDeployRouteImport } from './routes/technician/deploy'
import { Route as TechnicianDashboardRouteImport } from './routes/technician/dashboard'
import { Route as TechnicianBulkImportRouteImport } from './routes/technician/bulk-import'
import { Route as TechnicianAvRouteImport } from './routes/technician/av'
import { Route as TechnicianAddAssetRouteImport } from './routes/technician/add-asset'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianReturnRoute = TechnicianReturnRouteImport.update({
  id: '/technician/return',
  path: '/technician/return',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianNetworkRoute = TechnicianNetworkRouteImport.update({
  id: '/technician/network',
  path: '/technician/network',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianLaptopRoute = TechnicianLaptopRouteImport.update({
  id: '/technician/laptop',
  path: '/technician/laptop',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianDeployRoute = TechnicianDeployRouteImport.update({
  id: '/technician/deploy',
  path: '/technician/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianDashboardRoute = TechnicianDashboardRouteImport.update({
  id: '/technician/dashboard',
  path: '/technician/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianBulkImportRoute = TechnicianBulkImportRouteImport.update({
  id: '/technician/bulk-import',
  path: '/technician/bulk-import',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianAvRoute = TechnicianAvRouteImport.update({
  id: '/technician/av',
  path: '/technician/av',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianAddAssetRoute = TechnicianAddAssetRouteImport.update({
  id: '/technician/add-asset',
  path: '/technician/add-asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/technician/add-asset': typeof TechnicianAddAssetRoute
  '/technician/av': typeof TechnicianAvRoute
  '/technician/bulk-import': typeof TechnicianBulkImportRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/deploy': typeof TechnicianDeployRoute
  '/technician/laptop': typeof TechnicianLaptopRoute
  '/technician/network': typeof TechnicianNetworkRoute
  '/technician/return': typeof TechnicianReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/technician/add-asset': typeof TechnicianAddAssetRoute
  '/technician/av': typeof TechnicianAvRoute
  '/technician/bulk-import': typeof TechnicianBulkImportRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/deploy': typeof TechnicianDeployRoute
  '/technician/laptop': typeof TechnicianLaptopRoute
  '/technician/network': typeof TechnicianNetworkRoute
  '/technician/return': typeof TechnicianReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/technician/add-asset': typeof TechnicianAddAssetRoute
  '/technician/av': typeof TechnicianAvRoute
  '/technician/bulk-import': typeof TechnicianBulkImportRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/deploy': typeof TechnicianDeployRoute
  '/technician/laptop': typeof TechnicianLaptopRoute
  '/technician/network': typeof TechnicianNetworkRoute
  '/technician/return': typeof TechnicianReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/technician/add-asset'
    | '/technician/av'
    | '/technician/bulk-import'
    | '/technician/dashboard'
    | '/technician/deploy'
    | '/technician/laptop'
    | '/technician/network'
    | '/technician/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/technician/add-asset'
    | '/technician/av'
    | '/technician/bulk-import'
    | '/technician/dashboard'
    | '/technician/deploy'
    | '/technician/laptop'
    | '/technician/network'
    | '/technician/return'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/technician/add-asset'
    | '/technician/av'
    | '/technician/bulk-import'
    | '/technician/dashboard'
    | '/technician/deploy'
    | '/technician/laptop'
    | '/technician/network'
    | '/technician/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TechnicianAddAssetRoute: typeof TechnicianAddAssetRoute
  TechnicianAvRoute: typeof TechnicianAvRoute
  TechnicianBulkImportRoute: typeof TechnicianBulkImportRoute
  TechnicianDashboardRoute: typeof TechnicianDashboardRoute
  TechnicianDeployRoute: typeof TechnicianDeployRoute
  TechnicianLaptopRoute: typeof TechnicianLaptopRoute
  TechnicianNetworkRoute: typeof TechnicianNetworkRoute
  TechnicianReturnRoute: typeof TechnicianReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/return': {
      id: '/technician/return'
      path: '/technician/return'
      fullPath: '/technician/return'
      preLoaderRoute: typeof TechnicianReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/network': {
      id: '/technician/network'
      path: '/technician/network'
      fullPath: '/technician/network'
      preLoaderRoute: typeof TechnicianNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/laptop': {
      id: '/technician/laptop'
      path: '/technician/laptop'
      fullPath: '/technician/laptop'
      preLoaderRoute: typeof TechnicianLaptopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/deploy': {
      id: '/technician/deploy'
      path: '/technician/deploy'
      fullPath: '/technician/deploy'
      preLoaderRoute: typeof TechnicianDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/dashboard': {
      id: '/technician/dashboard'
      path: '/technician/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof TechnicianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/bulk-import': {
      id: '/technician/bulk-import'
      path: '/technician/bulk-import'
      fullPath: '/technician/bulk-import'
      preLoaderRoute: typeof TechnicianBulkImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/av': {
      id: '/technician/av'
      path: '/technician/av'
      fullPath: '/technician/av'
      preLoaderRoute: typeof TechnicianAvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/add-asset': {
      id: '/technician/add-asset'
      path: '/technician/add-asset'
      fullPath: '/technician/add-asset'
      preLoaderRoute: typeof TechnicianAddAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TechnicianAddAssetRoute: TechnicianAddAssetRoute,
  TechnicianAvRoute: TechnicianAvRoute,
  TechnicianBulkImportRoute: TechnicianBulkImportRoute,
  TechnicianDashboardRoute: TechnicianDashboardRoute,
  TechnicianDeployRoute: TechnicianDeployRoute,
  TechnicianLaptopRoute: TechnicianLaptopRoute,
  TechnicianNetworkRoute: TechnicianNetworkRoute,
  TechnicianReturnRoute: TechnicianReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
